import httpx
from kiota_abstractions.serialization.parse_node_factory_registry import ParseNodeFactoryRegistry
from msgraph.generated.models.external_connectors.connection_operation import ConnectionOperation
from msgraph.generated.models.external_connectors.connection_operation_status import ConnectionOperationStatus

token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6ImlmNmo0TjZaZFlreDdwSXE4X1VlUEpsYjQ4NEQ1Z0pjYTFXcHFEU0RmeTgiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83YjI4MjhiOS04OWEzLTQ1MDctOWUxYS0wNWZmNDZkMTE5MmQvIiwiaWF0IjoxNzIzMzI4NzI5LCJuYmYiOjE3MjMzMjg3MjksImV4cCI6MTcyMzMzMjYyOSwiYWlvIjoiRTJkZ1lIZ1RPZGR5OWdFNVA5M0xWcVhMUzFOZEFRPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJQeXRob25HQyIsImFwcGlkIjoiNmRjNTViNTQtYzUyMi00NjhlLWJkMGYtZDkxM2I4MTJiYTVjIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvN2IyODI4YjktODlhMy00NTA3LTllMWEtMDVmZjQ2ZDExOTJkLyIsImlkdHlwIjoiYXBwIiwib2lkIjoiYTMwYTgyZjEtY2UxNi00ZDEyLTkxNmMtODhhNjliNmI1MDYyIiwicmgiOiIwLkFYMEF1U2dvZTZPSkIwV2VHZ1hfUnRFWkxRTUFBQUFBQUFBQXdBQUFBQUFBQUFDYUFBQS4iLCJyb2xlcyI6WyJFeHRlcm5hbEl0ZW0uUmVhZFdyaXRlLk93bmVkQnkiLCJFeHRlcm5hbENvbm5lY3Rpb24uUmVhZFdyaXRlLk93bmVkQnkiLCJVc2VyLlJlYWQuQWxsIl0sInN1YiI6ImEzMGE4MmYxLWNlMTYtNGQxMi05MTZjLTg4YTY5YjZiNTA2MiIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjdiMjgyOGI5LTg5YTMtNDUwNy05ZTFhLTA1ZmY0NmQxMTkyZCIsInV0aSI6ImprTC1XWGlfbmsySGJ1SXZDLTBQQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjA5OTdhMWQwLTBkMWQtNGFjYi1iNDA4LWQ1Y2E3MzEyMWU5MCJdLCJ4bXNfaWRyZWwiOiI3IDgiLCJ4bXNfdGNkdCI6MTY1MjQyMjY1MH0.grdToqqHsuyK4fn47h9e2ExCR7997jPcjWfW58PSzHYHdk6GMUpFyNSs9IbWAJrt_WY2XX9uTmHlxT9H2-wT-yIwiTWZZi0NimZE73UHfS4m_n2rQTQSQGQkDlc2Ev9aU8TKdQyvYe_766yhvpnt5ucIXdHbztEm6wqV9nE8nJerwfkOG4vwTzh2h4H8NBuMKQ01UFio468upeGFSpbilwAyOd2D9lCIkdbiJVRF_e-d8j7xWM9X63IxPJYthqJcwnWEnY24fiwkyNHaO_unKYwmI4T2PPJaFX_J0vjOE1Fw90goCMOUjksZQo8yW0C_3mcJkqy8MjMvA_KaHny_2Q"
headers = {'Authorization': f'Bearer {token}'}

r = httpx.get("https://graph.microsoft.com/v1.0/external/connections/MKObjectSearch9/operations/1.eus-b.02138DAE59DBA899103B3CB109903B25.AADD007D4C985068AE7FF50FACE30FB3", headers=headers, verify=False)

body_bytes = r.read()
print(body_bytes)

parse_node = ParseNodeFactoryRegistry().get_root_parse_node("application/json", body_bytes)
print(parse_node)
#operation: ConnectionOperation = parse_node.get_object_value(ConnectionOperation.create_from_discriminator_value(parse_node))